# -*- coding: utf-8 -*-
"""Disaster_detection_model_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHFVnuuXbSUnPxquYqNi3RCv3xj6UFsP
"""

# Install required packages
!pip install tensorflow
!pip install albumentations
!pip install opencv-python

!pip install --upgrade tensorflow

!pip install --upgrade jax jaxlib tensorflow

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Import the training function
from train_enhanced import train_model

# Set parameters
DATA_DIR = "/content/drive/MyDrive/EmergencyNet/data/AIDER1"
IMG_SIZE = 224
BATCH_SIZE = 64
EPOCHS = 15

# Train model
model, history = train_model(DATA_DIR, IMG_SIZE, BATCH_SIZE, EPOCHS)